name: Go

on:
  push:
    branches: [ main, master]
  pull_request:
    branches: [ main, master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          goversion:
            - '1.16'
            - '1.17'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '${{ matrix.goversion }}'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Vet
      run: go vet ./...
